# Application properties that need to be
# embedded within the web application can be included here

cas:
  server:
    # 配置单点登录服务器访问地址
    name: http://127.0.0.1:8443
    prefix: ${cas.server.name}/cas
  authn:
    jdbc:
      query:
        - dialect: org.hibernate.dialect.MySQLDialect
          driverClass: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.34.171.57:3306/fishdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          user: root
          password: ymjpwd666
          fieldPassword: user_password
          sql: select * from user where user_name=?
#
#    accept:
#      # 设置登录账号和密码，默认为 casuser::Mellon
#      users: admin::admin
#  service-registry:
#    # 设置服务注册为json文件的方式
#    init-from-json: true
#    json:
#      #　服务注册时读取的json文件的位置
#      location: classpath:/services


server:
  ssl:
    # 关闭https访问，此处如果已经有了https证书，可以设为true
    enabled: false
